### ISSUE TITLE
Mobile images stretching

### ISSUE THREAD

**Issue by rootsup** [Pixabay/jQuery-flexImages#5] opened 2015-02-03 14:45 UTC
Not sure what is happening - thoughts? Only on mobile. 
![image](https://cloud.githubusercontent.com/assets/10824333/6022235/437f7eee-ab70-11e4-888f-2a83a3740ca1.jpg)
![image](https://cloud.githubusercontent.com/assets/10824333/6022238/43b09c7c-ab70-11e4-8e6a-5f9296ab9371.jpg)
![image](https://cloud.githubusercontent.com/assets/10824333/6022239/43b33ea0-ab70-11e4-8b39-e6b6f71f5731.jpg)
![image](https://cloud.githubusercontent.com/assets/10824333/6022237/43b0b27a-ab70-11e4-8fdb-dd1543a720b7.jpg)

**Comment by SimonSteinberger** [comment] 2015-02-03 15:09
Why did you open another issue?
https://github.com/Pixabay/jQuery-flexImages/issues/3
You can add information and explain things even if an issue is closed.

I can't see what you're talking about. In any case: the plugin makes no difference between mobile or non-mobile. So it's either a bug caused by the particular mobile browser or maybe it has to do with the lower width of the browser window.

Please explain in more detail what's the problem. Since I don't see anything here right now, I'm closing the issue. I'll reopen it if it's really a bug.

**Closed by SimonSteinberger** 2015-02-03 15:09 UTC
